apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/cesar-alejandro-perez/dispatcher-service/k8s?ref=32e1559a4a2beacbe3db84e3dcbdb126575e70c9

patches:
- path: patch-env.yml
- path: patch-resources.yml
- path: patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: dispatcher-config

images:
- name: dispatcher-service
  newName: ghcr.io/cesar-alejandro-perez/dispatcher-service
  newTag: 32e1559a4a2beacbe3db84e3dcbdb126575e70c9

replicas:
- count: 1
  name: dispatcher-service
