apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/cesar-alejandro-perez/order-service/k8s?ref=ce257f4c2dabf30237498c18662133f2ff0213fd

patches:
- path: patch-env.yml
- path: patch-resources.yml
- path: patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: order-config

images:
- name: order-service
  newName: ghcr.io/cesar-alejandro-perez/order-service
  newTag: ce257f4c2dabf30237498c18662133f2ff0213fd

replicas:
- count: 1
  name: order-service
