apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/cesar-alejandro-perez/order-service/k8s?ref=c8d29a38107eca8d3365cfbdbc3656070dae3a2c

patches:
- path: patch-env.yml
- path: patch-resources.yml
- path: patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: order-config

images:
- name: order-service
  newName: ghcr.io/cesar-alejandro-perez/order-service
  newTag: c8d29a38107eca8d3365cfbdbc3656070dae3a2c

replicas:
- count: 2
  name: order-service
