apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/cesar-alejandro-perez/edge-service/k8s?ref=661cabc0f527db866ae8e0ec83eb745cebec6790

patches:
- path: patch-env.yml
- path: patch-ingress.yml
- path: patch-resources.yml
- path: patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: edge-config

images:
- name: edge-service
  newName: ghcr.io/cesar-alejandro-perez/edge-service
  newTag: 661cabc0f527db866ae8e0ec83eb745cebec6790

replicas:
- count: 1
  name: edge-service
